site_name: Alt Markets Docs
site_url: https://docs.alt.markets
site_description: Documentation & Resources for Alt Markets
site_author: Alt Markets
docs_dir: content
theme:
  name: material
  language: en
  show_sidebar: true
  palette:
    primary: black
    accent: black
    scheme: slate
  font:
    text: Roboto Mono
  features:
    - navigation.instant
  icon:
    logo: fontawesome/solid/chart-line
extra:
  generator: false # Remove footer note
  analytics:
    provider: google
    property: G-VK68V6SMEV
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AltMarketsHQ
      name: Alt Markets on Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/AltMarketsHQ
      name: Alt Markets on Telegram
copyright: Copyright &copy; Alt Markets
plugins:
  - search
  - awesome-pages